config/routes.rb
Rails.application.routes.draw do

  get '/about', to: "static_pages#about"

  get "/contact", to: "static_pages#contact"

  get "/instructions", to: "static_pages#instructions"

  get "/rules", to: "static_pages#rules"
  
  get '/registration', to: "teams#new"
  
  get '/teams', to: "teams#index"
  
  root "static_pages#home"
  
  resources :teams 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name,      presence: true 
  validates :member1,   presence: true
  validates :member2,   presence: true
  validates :member3,   presence: true
  validates :email,     presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def about
  end

  def contact
  end

  def instructions
  end

  def rules
  end

  def results
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_filter :authenticate, only: [:index]

  def authenticate
    authenticate_or_request_with_http_basic('Administration') do |username, password|
      username == 'admin' && password == 'password'
    end
  end
  
  def new
    @team = Team.new 
  end
  
  def destroy
    Team.find(params[:id]).destroy
    flash[:success] = "Team deleted"
    redirect_to teams_url
  end
  
  def create
    @team = Team.new(team_params)
    
    if @team.save
      TeamMailer.registration_confirmation(@team).deliver_now
      flash[:success] = "Thank you for registering! A confirmation email has also been sent."
      redirect_to root_path 
    else
      flash[:danger] = "Please, make sure that the form is filled in properly."
      render 'new'
    end
  end
  
  def index 
    @teams = Team.all
  end
  
  
  private
    def team_params
      params.require(:team).permit(:name, :member1, :member2, :member3, :email, :race_type)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
  
  def team_number(teams, type)
    count = 0 
      teams.each do | team |
        if team.race_type == type
          count += 1
        end
      end
    count
  end
  
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <small>
        <p>&copy; Teknologföreningen 2017</p>
      </small>
      <nav>
        <ul>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><a href="https://www.facebook.com/events/115885275735764/">Facebook</a></li>
        </ul>
      </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="header clearfix container">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
            EVENT INFO <b class="caret"></b>
          </a>
           <ul class="dropdown-menu">
             <li><%= link_to "Instructions", instructions_path %></li>
             <li><%= link_to "Rules", rules_path %></li>
           </ul>
        </li>
        <li role="presentation"><%= link_to "CONTACT", contact_path%></li>
      </ul>
    </nav>
    <div class="logo">
      <%= link_to image_tag("tfextremlogo.png", alt:"logo", height:"40"), root_path %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> - TF XTREME</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
       <% flash.each do |message_type, message| %>
         <div class="alert alert-<%= message_type %>"><%= message %></div>
       <% end %>
       <%= yield %>
       <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, 'About') %> 
<p>TF Xtreme Challenge Endurance is the adventure race 
   where competitors get to test their limits, both physical and mental.<br><br>

  This years competition will be more focused on endurance and strength
  than the previous competitions and there will be a bit fewer checkpoints.
  25 teams complete the course consisting of 40-50 km cycling
  and a bit of running combined with a number of physically and mentally challenging checkpoints.<br><br>
  
  Do YOU have the guts to participate?
  Don't miss the toughest, funniest and most unforgettable extreme sports competition of the year.
  Last year the event was sold out in advance, so be quick this year!<br><br>
  The sign-up will open on the 8th of September 12.00.<br><br>
  WHAT? An extreme sport competition for students. 3 persons / team<br>
  WHEN? The 23rd of September 2017 10 am<br>
  WHERE? Startpoint at Alvarin Aukio, Otaniemi<br>
  PRICE? 15 € / person (45 € / team)
</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Contact') %>
<p>Email: xtremist@teknologforeningen.fi </p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home" ) %> 
<div class="jumbotron">
  <div class="dark-square">
      <div class="opacity-1">
        <h1>GET READY</h1>
        <h1>23.9.2017</h1>
        <p class="lead">You do not want to miss this adventure.</p>
        <p class="lead">Register your winner team right now!</p>
        <p><a class="btn btn-lg btn-success" href="/registration" role="button">REGISTER TEAM</a></p>
      </div>
  </div>
</div>
<p>TF Xtreme Challenge Endurance is the adventure race 
   where competitors get to test their limits, both physical and mental.<br><br>

  This years competition will be more focused on endurance and strength
  than the previous competitions and there will be a bit fewer checkpoints.
  25 teams complete the course consisting of 40-50 km cycling
  and a bit of running combined with a number of physically and mentally challenging checkpoints.<br><br>
  
  Do YOU have the guts to participate?<br><br>
  Don't miss the toughest, funniest and most unforgettable extreme sports competition of the year.
  Last year the event was sold out in advance, so be quick this year!<br><br>
  The sign-up will open on the 8th of September 12.00.</p>

app/views/static_pages/instructions.html.erb
<%= provide(:title, "Instructions") %>
<div class="row marketing">
  <div class="col-lg">
    <h4>Distances and tasks during the race:</h4>
    <p>The course consists of 40-50 km cycling and a bit of running combined with a number of physically and mentally challenging checkpoints.</p>
    
    <h4>Start:</h4>
    <p>The race starts from Alvarin Aukio in Otaniemi at 10 am on Sat 23th September. Before the start each team must take part in race briefing, the time of which will be announced as the event approaches. Teams will start with 5-minute intervals.</p>
    <p>Contestants may leave their belongings (eg. valuables, warmup and reserve clothes) in a 100-litre plastic bag that will be transported to the vicinity of the goal by race organizers. The bag will be clearly marked with the team’s race number and the whole team will use the same bag.</p>
  
    <h4>Transference during race:</h4>
    <p>Teams will move from checkpoint to another using their own bikes. If a race organizer hasn’t defined a specific route to the next checkpoint, it is up to the contestants to figure out their way there. Usage of any kind of GPS or other tracking devices during the race is strictly forbidden. The overall route has been designed so that there will be no roads worse than a well-mainained gravel road. Considering the nature of the race, one should still leave their over-expensive race bike home.</p>
  
    <h4>EMIT-timing:</h4>
    <p>Having arrived in the start area, each team will be given an EMIT-timing chip to use during the race. Each checkpoint will have two different EMIT receivers:</p>
    <p>START – Tag when your team arrives at the checkpoint.</p>
    <p>END – Tag when your team has completed the task or is about to perform the task. END will therefore be always tagged corresponding to the instructions given by the checkpoint staff.</p>
    <p>Tag when your team has completed the task or is about to perform the task. END will therefore be always tagged corresponding to the instructions given by the checkpoint staff.</p>
    <p>The time between tagging START and END will be subtracted from the total race time. Any misuse of EMIT devices will result in a time penalty.</p>
  
    <h4>Checkpoints:</h4>
    <p>As soon as your team arrives at a checkpoint you have to tag START. From that on, each team waits until checkpoint personnel gives them information about performing the checkpoint’s task. Should more than one team arrive at a checkpoint simultaneously or if there is already a queue, the teams will queue in the order they arrived at the checkpoint.</p>
    <p>If END is tagged before completing a task in a checkpoint, the time spent in the checkpoint will be included in the total race time. In this case the team is allowed to exit the checkpoint as soon as they have completed the task.</p>
    <p>At most of the checkpoints END is tagged no sooner than after the completion of the task in that checkpoint. In these cases the time spent at the checkpoint will not be included in total race time. On the contrary, performing well will result in a reduction of total race time.</p>
    <p>Checkpoint personnel will always tell your team when to tag END. Please, do ask whenever feeling unsure! As a result of skipping a task or clearly violating staff’s instructions the team will get a time penalty.</p>
  
    <h4>Goal:</h4>
    <p>The goal is found near Otaniemi. Your team’s plastic bag with its contents will be transported to the goal area as the race starts. In the goal area, it is possible to sauna.</p>
  
    <h4>Food and drink checkpoints:</h4>
    <p>There will be several food and drink checkpoints during the race. More specific information on these will be announced later.</p>
  </div>
</div>

app/views/static_pages/rules.html.erb
<%= provide(:title, "Rules") %>
<div class="row marketing">
  <div class="col-lg">
    <h4>General:</h4>
    <ul>
      <li>The team consist of three (3) students. Valid student cards must be shown when asked.</li>
      <li>The competitors must be at least 18 years old, healthy and be in a sufficiently good shape.</li>
      <li>The competitors must have swimming and orienteering competence. If you have any questions, feel free to ask before the competition.</li>
      <li>The competitors are responsible for their own insurance, the organizers do not have any responsibility for injuries or broken equipment during the race.</li>    
      <li>The registration is binding, but team members can be changed until three days before the competition by contacting the head race organizer. After this day changes are valid only by doctor's certificate.</li>
    </ul>

    <h4>The competition:</h4>
    <ul>
      <li>The competitors are obligated to follow all directives and guidelines given by the organizers. They must also carefully read trough all rules.</li>
      <li>Traffic rules must be followed at all times! If a competitor is seen breaking traffic rules or cycling without a helmet, the organizers have the right to disqualify the team.</li>
      <li>The race consist of 10-20 checkpoints, between which the competitors travel by bike.</li>  
      <li>The team members have to take care that they are eating and drinking enough during the race.</li>
      <li>Total distances and some of the checkpoints are listed in race instructions, but the team should also be ready for surprise checkpoints.</li>
      <li>The competition time is calculated for the whole race, only possible queue times are taken off.</li>
      <li>All checkpoints are held by professional and competent instructors, which safety orders and instructions should be followed at all times.</li>
      <li>The highest permitted distance between two team members is 50 meters. Longer distances are only allowed if a checkpoint needs it, and then also only if an organizers gives permission.</li>
    </ul>

    <h4>Registration:</h4>
    <ul>
      <li>The registration for the competition opens 12:00 8.9 and closes after 30 teams have signed up.</li>
      <li>After registration the team receives a confirmation e-mail with a bill for the registration fee. The registration fee should be paid on the given bank account within seven days from registration. The payments will be checked before the competition, and teams can be asked to bring a receipt of the payment to the competition (if the payment has been done later than 20.9).</li>
      <li>The team will receive more information about the competition before the race day.</li>
    </ul>
    
    <h4>Cutting the competition:</h4>
    <ul>
      <li>If one member of the team is forced to cut, the other ones can, if they want, continue the race with a two member team. The cutting must be informed to the competition leader as fast as possible.</li>
      <li>The other members can continue the competition, but they no longer participate in the competition team. Therfore, they must be ready to give space for teams that are still competing if needed.</li>
    </ul>
    
    <h4>Checkpoints:</h4>
    <ul>
      <li>During the race the team will meet adventure checkpoints, which will test the competitors physical, mental, logical strenght, as well as team skills and courage.</li>
      <li>The teams perform the checkpoints in the order they arrived, according to organizers instructions.</li>
      <li>The team can always choose to not perform a checkpoint, which will give them a time-penalty.</li>
      <li>During the competition an EMIT- based timekeeping system is used. The teams are obligated to pay (80 €) for a missing EMIT after the race. The report of the missing EMIT should be done as fast as possible so the competitors can continue the race without the EMIT.</li>
    </ul>
    
    <h4>Other:</h4>
    <ul>
      <li>Any protest must be reported immediately when the team has passed the gold line. The race judiciary will treat the protest immediately.</li>
      <li>The competitors are not allowed to aggravate other team's performance.</li>
      <li>The organizers are allowed to disqualify teams that have broken the competition rules.</li>
      <li>The competition shirts(will be given) must be visible during the whole race.</li>
      <li>The organizers are allowed to change rules before and during the competition. Competitors should always be informed of these changes.</li>
      <li>The organizers can give additional instructions during the race. All competitors must follow these, even though it would break any of the rules listed here or on the competition paper.</li>
    </ul>
  </div>
</div>